version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql+psycopg2://postgres:567234@db:5432/hw02
